name: Generate Snake

on:
  schedule:
    - cron: "29 12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: S-KishoreBabu  # Correct GitHub username
          outputs: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
      
      # Push the generated SVG to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: master  # Change to "main" if using the "main" branch for GitHub Pages
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
